### ISSUE TITLE
[music-player] The `MusicEqualizerStick` can be black, making the sticks indistinguishable.

### ISSUE THREAD

**Issue by junhoyeo** [anaclumos/dynamic-island#3]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/32605822/208269086-4a9029e7-0f5b-49dd-94ab-077f4811cbca.png">

<img width="691" alt="image" src="https://user-images.githubusercontent.com/32605822/208269101-470c93e2-3d4b-48b4-af5b-08f7c55dde59.png">

**Comment by anaclumos** [comment]
Hey @junhoyeo, Apple Music is returning black as the primary key color. Maybe we can set the min value of the paint.

**Comment by anaclumos** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/31657298/217684954-0bc4b9be-5a7b-43d2-b0bb-94840f8b8f75.png">

**Comment by junhoyeo** [comment]
@anaclumos, Looks good! Thanks!
